# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aeafcf8c26b6d53239b9f40ea96cb9453e7208f0318eee6872256f01879b48b7a093681980b10795e0c1cce9de9a3ca1281919503a2d6f1b646b8e4d57204520

test:
  secret_key_base: d866572a6f9963485d18d00e20acd276e12163c118bc7b2d018885bc37e208a64ab4c4d77970ddf9927b33b6b593f434b4ed10e321c516c218bd08ab3d9c2bb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
